apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stage  # <-- optional if you're applying in a namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: charansait372/backend:v1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-secret-volume
              mountPath: /etc/secrets/db
              readOnly: true
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-secret

