apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: charansait372/backend:v1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volume:
        - name: db-secret
          secret:
            secretName: db-secret

